//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smashgg_to_liquipedia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LpStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LpStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smashgg_to_liquipedia.LpStrings", typeof(LpStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Box|break|padding=4em}}.
        /// </summary>
        internal static string BoxBreak {
            get {
                return ResourceManager.GetString("BoxBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Box|end}}.
        /// </summary>
        internal static string BoxEnd {
            get {
                return ResourceManager.GetString("BoxEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Box|start|padding=4em}}.
        /// </summary>
        internal static string BoxStart {
            get {
                return ResourceManager.GetString("BoxStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{win}}.
        /// </summary>
        internal static string Checkmark {
            get {
                return ResourceManager.GetString("Checkmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |p1=.
        /// </summary>
        internal static string DoublesSlotP1 {
            get {
                return ResourceManager.GetString("DoublesSlotP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |p1flag=.
        /// </summary>
        internal static string DoublesSlotP1Flag {
            get {
                return ResourceManager.GetString("DoublesSlotP1Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |p2=.
        /// </summary>
        internal static string DoublesSlotP2 {
            get {
                return ResourceManager.GetString("DoublesSlotP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |p2flag=.
        /// </summary>
        internal static string DoublesSlotP2Flag {
            get {
                return ResourceManager.GetString("DoublesSlotP2Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{DoublesGroupTableSlot.
        /// </summary>
        internal static string DoublesSlotStart {
            get {
                return ResourceManager.GetString("DoublesSlotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |dq=.
        /// </summary>
        internal static string DQ {
            get {
                return ResourceManager.GetString("DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{GroupTableEnd}}.
        /// </summary>
        internal static string GroupEnd {
            get {
                return ResourceManager.GetString("GroupEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{GroupTableStart |.
        /// </summary>
        internal static string GroupStart {
            get {
                return ResourceManager.GetString("GroupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |width=300px}}.
        /// </summary>
        internal static string GroupStartWidth {
            get {
                return ResourceManager.GetString("GroupStartWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string LRound {
            get {
                return ResourceManager.GetString("LRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Match list end}}.
        /// </summary>
        internal static string MatchListEnd {
            get {
                return ResourceManager.GetString("MatchListEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Match list start.
        /// </summary>
        internal static string MatchListStart {
            get {
                return ResourceManager.GetString("MatchListStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Match stages.
        /// </summary>
        internal static string MatchStages {
            get {
                return ResourceManager.GetString("MatchStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}.
        /// </summary>
        internal static string MatchStagesEnd {
            get {
                return ResourceManager.GetString("MatchStagesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p1.
        /// </summary>
        internal static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p2.
        /// </summary>
        internal static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |bg=.
        /// </summary>
        internal static string SlotBg {
            get {
                return ResourceManager.GetString("SlotBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}.
        /// </summary>
        internal static string SlotEnd {
            get {
                return ResourceManager.GetString("SlotEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |flag=.
        /// </summary>
        internal static string SlotFlag {
            get {
                return ResourceManager.GetString("SlotFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |lose_m=.
        /// </summary>
        internal static string SlotMLoss {
            get {
                return ResourceManager.GetString("SlotMLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |win_m=.
        /// </summary>
        internal static string SlotMWin {
            get {
                return ResourceManager.GetString("SlotMWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |pbg=.
        /// </summary>
        internal static string SlotPbg {
            get {
                return ResourceManager.GetString("SlotPbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |place=.
        /// </summary>
        internal static string SlotPlace {
            get {
                return ResourceManager.GetString("SlotPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{GroupTableSlot|.
        /// </summary>
        internal static string SlotStart {
            get {
                return ResourceManager.GetString("SlotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}.
        /// </summary>
        internal static string SortEnd {
            get {
                return ResourceManager.GetString("SortEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{HiddenSort|.
        /// </summary>
        internal static string SortStart {
            get {
                return ResourceManager.GetString("SortStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stage.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t1.
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t2.
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        internal static string WRound {
            get {
                return ResourceManager.GetString("WRound", resourceCulture);
            }
        }
    }
}
