//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smashgg_api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmashggStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmashggStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smashgg_api.SmashggStrings", typeof(SmashggStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayIdentifier.
        /// </summary>
        internal static string DisplayIdent {
            get {
                return ResourceManager.GetString("DisplayIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrants.
        /// </summary>
        internal static string Entrants {
            get {
                return ResourceManager.GetString("Entrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phaseId.
        /// </summary>
        internal static string PhaseId {
            get {
                return ResourceManager.GetString("PhaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets.
        /// </summary>
        internal static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/phase/.
        /// </summary>
        internal static string UrlPrefixPhase {
            get {
                return ResourceManager.GetString("UrlPrefixPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/phase_group/.
        /// </summary>
        internal static string UrlPrefixPhaseGroup {
            get {
                return ResourceManager.GetString("UrlPrefixPhaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/tournament/.
        /// </summary>
        internal static string UrlPrefixTourney {
            get {
                return ResourceManager.GetString("UrlPrefixTourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?expand[]=groups.
        /// </summary>
        internal static string UrlSuffixPhase {
            get {
                return ResourceManager.GetString("UrlSuffixPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?expand[]=sets&amp;expand[]=entrants.
        /// </summary>
        internal static string UrlSuffixPhaseGroup {
            get {
                return ResourceManager.GetString("UrlSuffixPhaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waveId.
        /// </summary>
        internal static string WaveId {
            get {
                return ResourceManager.GetString("WaveId", resourceCulture);
            }
        }
    }
}
