//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smashgg_to_liquipedia.Smashgg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmashggStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmashggStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smashgg_to_liquipedia.Smashgg.SmashggStrings", typeof(SmashggStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayIdentifier.
        /// </summary>
        internal static string DisplayIdent {
            get {
                return ResourceManager.GetString("DisplayIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayRound.
        /// </summary>
        internal static string DisplayRound {
            get {
                return ResourceManager.GetString("DisplayRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entities.
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1CharacterIds.
        /// </summary>
        internal static string Entrant1CharList {
            get {
                return ResourceManager.GetString("Entrant1CharList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1Id.
        /// </summary>
        internal static string Entrant1Id {
            get {
                return ResourceManager.GetString("Entrant1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1P1CharacterId.
        /// </summary>
        internal static string Entrant1P1char {
            get {
                return ResourceManager.GetString("Entrant1P1char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1P1Stocks.
        /// </summary>
        internal static string Entrant1P1stocks {
            get {
                return ResourceManager.GetString("Entrant1P1stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P1CharacterId.
        /// </summary>
        internal static string Entrant1P2char {
            get {
                return ResourceManager.GetString("Entrant1P2char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P1Stocks.
        /// </summary>
        internal static string Entrant1P2stocks {
            get {
                return ResourceManager.GetString("Entrant1P2stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1PrereqId.
        /// </summary>
        internal static string Entrant1PrereqId {
            get {
                return ResourceManager.GetString("Entrant1PrereqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1Score.
        /// </summary>
        internal static string Entrant1Score {
            get {
                return ResourceManager.GetString("Entrant1Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant1PrereqType.
        /// </summary>
        internal static string Entrant1Type {
            get {
                return ResourceManager.GetString("Entrant1Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2CharacterIds.
        /// </summary>
        internal static string Entrant2CharList {
            get {
                return ResourceManager.GetString("Entrant2CharList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2Id.
        /// </summary>
        internal static string Entrant2Id {
            get {
                return ResourceManager.GetString("Entrant2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P1CharacterId.
        /// </summary>
        internal static string Entrant2P1char {
            get {
                return ResourceManager.GetString("Entrant2P1char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P1Stocks.
        /// </summary>
        internal static string Entrant2P1stocks {
            get {
                return ResourceManager.GetString("Entrant2P1stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P2CharacterId.
        /// </summary>
        internal static string Entrant2P2char {
            get {
                return ResourceManager.GetString("Entrant2P2char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2P2Stocks.
        /// </summary>
        internal static string Entrant2P2stocks {
            get {
                return ResourceManager.GetString("Entrant2P2stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2PrereqId.
        /// </summary>
        internal static string Entrant2PrereqId {
            get {
                return ResourceManager.GetString("Entrant2PrereqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2Score.
        /// </summary>
        internal static string Entrant2Score {
            get {
                return ResourceManager.GetString("Entrant2Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrant2PrereqType.
        /// </summary>
        internal static string Entrant2Type {
            get {
                return ResourceManager.GetString("Entrant2Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrantId.
        /// </summary>
        internal static string EntrantId {
            get {
                return ResourceManager.GetString("EntrantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrants.
        /// </summary>
        internal static string Entrants {
            get {
                return ResourceManager.GetString("Entrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videogameId.
        /// </summary>
        internal static string GameId {
            get {
                return ResourceManager.GetString("GameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderNum.
        /// </summary>
        internal static string GameOrder {
            get {
                return ResourceManager.GetString("GameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamerTag.
        /// </summary>
        internal static string Gamertag {
            get {
                return ResourceManager.GetString("Gamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isGF.
        /// </summary>
        internal static string IsGF {
            get {
                return ResourceManager.GetString("IsGF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lPlacement.
        /// </summary>
        internal static string lPlace {
            get {
                return ResourceManager.GetString("lPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lProgressingPhaseGroupId.
        /// </summary>
        internal static string lProgressingPhaseGroup {
            get {
                return ResourceManager.GetString("lProgressingPhaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mutations.
        /// </summary>
        internal static string Mutations {
            get {
                return ResourceManager.GetString("Mutations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to originalRound.
        /// </summary>
        internal static string OriginalRound {
            get {
                return ResourceManager.GetString("OriginalRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participantIds.
        /// </summary>
        internal static string ParticipantIds {
            get {
                return ResourceManager.GetString("ParticipantIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phaseId.
        /// </summary>
        internal static string PhaseId {
            get {
                return ResourceManager.GetString("PhaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placement.
        /// </summary>
        internal static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playerIds.
        /// </summary>
        internal static string PlayerIds {
            get {
                return ResourceManager.GetString("PlayerIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selections.
        /// </summary>
        internal static string Selections {
            get {
                return ResourceManager.GetString("Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectionType.
        /// </summary>
        internal static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectionValue.
        /// </summary>
        internal static string SelectionValue {
            get {
                return ResourceManager.GetString("SelectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets.
        /// </summary>
        internal static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stageId.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/phase/.
        /// </summary>
        internal static string UrlPrefixPhase {
            get {
                return ResourceManager.GetString("UrlPrefixPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/phase_group/.
        /// </summary>
        internal static string UrlPrefixPhaseGroup {
            get {
                return ResourceManager.GetString("UrlPrefixPhaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.smash.gg/tournament/.
        /// </summary>
        internal static string UrlPrefixTourney {
            get {
                return ResourceManager.GetString("UrlPrefixTourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;expand[]=seeds.
        /// </summary>
        internal static string UrlSuffixAdditionSeeds {
            get {
                return ResourceManager.GetString("UrlSuffixAdditionSeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;expand[]=standings.
        /// </summary>
        internal static string UrlSuffixAdditionStandings {
            get {
                return ResourceManager.GetString("UrlSuffixAdditionStandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?expand[]=groups.
        /// </summary>
        internal static string UrlSuffixPhase {
            get {
                return ResourceManager.GetString("UrlSuffixPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?expand[]=entrants&amp;expand[]=sets.
        /// </summary>
        internal static string UrlSuffixPhaseGroup {
            get {
                return ResourceManager.GetString("UrlSuffixPhaseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waveId.
        /// </summary>
        internal static string WaveId {
            get {
                return ResourceManager.GetString("WaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winnerId.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wPlacement.
        /// </summary>
        internal static string wPlace {
            get {
                return ResourceManager.GetString("wPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wProgressingPhaseGroupId.
        /// </summary>
        internal static string wProgressingPhaseGroup {
            get {
                return ResourceManager.GetString("wProgressingPhaseGroup", resourceCulture);
            }
        }
    }
}
